---
abstract: 'Perl-Net-Douban based on Moose and XML::Atom'
author:
  - woosley.xu
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092200'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Net-Douban
requires:
  Any::Moose: 0.09
  Moose: 0.81
  Scalar::Util: 0
  XML::Atom: 0.35
version: 0.13
